name: ibd
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.10.14
  - fastp
  - ca-certificates
  - openssl
  - bioconda::vsearch
  - conda-forge::r-base
  - click
  - pip=23.3.1
