name: ibd
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.10.4
  - fastp
  - ca-certificates
  - openssl
  - bioconda::vsearch
  - conda-forge::r-base
  - click
  - pip:
      - absl-py==2.0.0
      - anyio==4.1.0
      - appnope==0.1.3
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asttokens==2.4.1
      - astunparse==1.6.3
      - async-lru==2.0.4
      - attrs==23.1.0
      - babel==2.13.1
      - beautifulsoup4==4.12.2
      - biom-format==2.1.16
      - bleach==6.1.0
      - cachetools==5.3.2
      - certifi==2023.11.17
      - cffi==1.16.0
      - charset-normalizer==3.3.2
      - cloudpickle==3.0.0
      - comm==0.2.0
      - contourpy==1.2.0
      - cycler==0.12.1
      - debugpy==1.8.0
      - decorator==5.1.1
      - defusedxml==0.7.1
      - dill==0.3.8
      - dm-tree==0.1.8
      - et-xmlfile==1.1.0
      - exceptiongroup==1.2.0
      - executing==2.0.1
      - fastjsonschema==2.19.0
      - flatbuffers==24.3.25
      - fonttools==4.46.0
      - fqdn==1.5.1
      - gast==0.4.0
      - google-auth==2.24.0
      - google-auth-oauthlib==1.0.0
      - google-pasta==0.2.0
      - grpcio==1.59.3
      - h5py==3.10.0
      - idna==3.6
      - ipykernel==6.27.1
      - ipython==8.18.1
      - isoduration==20.11.0
      - jedi==0.19.1
      - jinja2==3.1.2
      - joblib==1.3.2
      - json5==0.9.14
      - jsonpointer==2.4
      - jsonschema==4.20.0
      - jsonschema-specifications==2023.11.2
      - jupyter-client==8.6.0
      - jupyter-core==5.5.0
      - jupyter-events==0.9.0
      - jupyter-lsp==2.2.1
      - jupyter-server==2.11.2
      - jupyter-server-terminals==0.4.4
      - jupyterlab==4.0.9
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.25.2
      - keras==3.5.0
      - keras-nightly==3.5.0.dev2024090903
      - kiwisolver==1.4.5
      - libclang==16.0.6
      - llvmlite==0.41.1
      - markdown==3.5.1
      - markdown-it-py==3.0.0
      - markupsafe==2.1.3
      - matplotlib==3.8.2
      - matplotlib-inline==0.1.6
      - mdurl==0.1.2
      - mistune==3.0.2
      - ml-dtypes==0.3.2
      - namex==0.0.8
      - natsort==8.4.0
      - nbclient==0.9.0
      - nbconvert==7.12.0
      - nbformat==5.9.2
      - nest-asyncio==1.5.8
      - notebook==7.0.6
      - notebook-shim==0.2.3
      - numba==0.58.1
      - numpy==1.24.3
      - oauthlib==3.2.2
      - openpyxl==3.1.5
      - opt-einsum==3.3.0
      - optree==0.12.1
      - overrides==7.4.0
      - packaging==23.2
      - pandas==2.1.3
      - pandocfilters==1.5.0
      - parso==0.8.3
      - pexpect==4.9.0
      - pillow==10.1.0
      - platformdirs==4.1.0
      - prometheus-client==0.19.0
      - prompt-toolkit==3.0.41
      - protobuf==4.25.1
      - psutil==5.9.6
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pyaml==24.7.0
      - pyasn1==0.5.1
      - pyasn1-modules==0.3.0
      - pycparser==2.21
      - pygments==2.17.2
      - pyparsing==3.1.1
      - python-dateutil==2.8.2
      - python-json-logger==2.0.7
      - pytz==2023.3.post1
      - pyyaml==6.0.1
      - pyzmq==25.1.1
      - referencing==0.31.1
      - requests==2.31.0
      - requests-oauthlib==1.3.1
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==13.8.0
      - rpds-py==0.13.2
      - rsa==4.9
      - scikeras==0.13.0
      - scikit-bio==0.6.1
      - scikit-learn==1.5.1
      - scikit-optimize==0.10.2
      - scipy==1.11.4
      - seaborn==0.13.0
      - send2trash==1.8.2
      - shap==0.43.0
      - six==1.16.0
      - slicer==0.0.7
      - sniffio==1.3.0
      - soupsieve==2.5
      - stack-data==0.6.3
      - tb-nightly==2.18.0a20240908
      - tensorboard==2.16.2
      - tensorboard-data-server==0.7.2
      - tensorflow==2.16.2
      - tensorflow-addons==0.23.0
      - tensorflow-estimator==2.13.0
      - tensorflow-io-gcs-filesystem==0.37.1
      - tensorflow-macos==2.16.2
      - tensorflow-probability==0.24.0
      - termcolor==2.4.0
      - terminado==0.18.0
      - threadpoolctl==3.2.0
      - tinycss2==1.2.1
      - tomli==2.0.1
      - tornado==6.4
      - tqdm==4.66.1
      - traitlets==5.14.0
      - typeguard==2.13.3
      - types-python-dateutil==2.8.19.14
      - typing-extensions==4.5.0
      - tzdata==2023.3
      - uri-template==1.3.0
      - urllib3==2.1.0
      - wcwidth==0.2.12
      - webcolors==1.13
      - webencodings==0.5.1
      - websocket-client==1.7.0
      - werkzeug==3.0.1
      - wrapt==1.16.0
